language: node_js
env:
  global:
    - API_SERVER=https://neteasecloudmusicapi-rdyawwwkoh.now.sh
node_js:
  - "12"
script:
  - yarn build
  - bash ./deploy-to-github.sh
cache:
  yarn: true

# deploy:
#   edge:
#     branch: v1.8.47
#   provider: pages
#   skip_cleanup: true
#   github_token: $GIT_TOKEN
#   keep_history: true
#   local_dir: dist
#   on:
#     branch: master